os: Visual Studio 2015

version: 1.0.3.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://download.microsoft.com/download/1/4/1/141760B3-805B-4583-B17C-8C5BC5A876AB/Installers/dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe'
- cmd: dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore .\src\WebDAV-Client -v Minimal
- dotnet build .\src\WebDAV-Client\project.json -c %CONFIGURATION%
- dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o .\artifacts .\src\WebDAV-Client\project.json

- appveyor-retry dotnet restore .\test\WebDAV-Client.Tests -v Minimal
- dotnet build .\test\WebDAV-Client.Tests\project.json -c %CONFIGURATION%

- appveyor-retry nuget restore .\test\WebDAV-Client.Tests.Net452\WebDAV-Client.Tests.Net452.csproj -PackagesDirectory packages

test_script:
- dotnet test -c %CONFIGURATION% --no-build .\test\WebDAV-Client.Tests.Net452

artifacts:
- path: artifacts\**\*.*

cache:
- packages